name: CI_events-api

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        run: docker build -t events-api:latest .

      - name: Run docker container
        run: docker run -d -p 5000:5000 --name events-api events-api:latest

